# Generated by Django 5.2.17 on 2026-08-18 12:22

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('view', "Ko'rish"), ('contact', 'Aloqa'), ('favorite', 'Saqlash')], max_length=12)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "E'lon hodisasi",
                'verbose_name_plural': "E'lon hodisalari",
                'ordering': ['-created_at'],
            },
        ),
    ]
