# Generated by Django 5.2.17 on 2026-08-18 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listingevent',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='listingevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='listingevent',
            index=models.Index(fields=['listing', 'event_type', 'created_at'], name='analytics_l_listing_1ff51f_idx'),
        ),
    ]
