# Generated by Django 5.2.17 on 2026-08-27 05:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_initial'),
        ('listings', '0003_alter_listing_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlandi'), ('declined', 'Rad etildi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=16)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_received', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='chat.conversation')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_initiated', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='listings.listing')),
            ],
            options={
                'verbose_name': "Band qilish so'rovi",
                'verbose_name_plural': "Band qilish so'rovlari",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['listing', 'status'], name='reservation_listing_8ab840_idx'), models.Index(fields=['candidate', 'status'], name='reservation_candida_1a9640_idx')],
            },
        ),
    ]
