# Generated by Django 5.2.17 on 2026-08-18 12:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('label_uz', models.CharField(max_length=120)),
                ('icon', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name': 'Qulaylik',
                'verbose_name_plural': 'Qulayliklar',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('price', models.PositiveBigIntegerField(help_text="Oylik ijara narxi (so'm)")),
                ('currency', models.CharField(default='UZS', max_length=8)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('pending_review', "Ko'rib chiqilmoqda"), ('ai_checking', 'AI tekshirilmoqda'), ('needs_review', "Qo'shimcha tekshiruv talab qilinadi"), ('approved', 'Tasdiqlangan'), ('published', "E'lon qilingan"), ('paused', "To'xtatilgan"), ('rejected', 'Rad etilgan'), ('expired', "Muddati o'tgan"), ('rented', 'Ijaraga berilgan'), ('deleted', "O'chirilgan")], db_index=True, default='draft', max_length=24)),
                ('views', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('moderation_note', models.CharField(blank=True, max_length=500)),
                ('auto_renew', models.BooleanField(default=True, help_text='Muddati tugaganda avtomatik yangilash')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "E'lon",
                'verbose_name_plural': "E'lonlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='listings/%Y/%m/')),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='listings/thumbs/%Y/%m/')),
                ('phash', models.CharField(blank=True, db_index=True, max_length=16)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'verbose_name': "E'lon rasmi",
                'verbose_name_plural': "E'lon rasmlari",
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=24)),
                ('to_status', models.CharField(max_length=24)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_status_changes', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='listings.listing')),
            ],
            options={
                'verbose_name': "E'lon holati tarixi",
                'verbose_name_plural': "E'lon holati tarixlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property_type', models.CharField(choices=[('apartment', 'Kvartira'), ('house', 'Uy'), ('room', 'Xona'), ('office', 'Ofis'), ('commercial', 'Tijorat')], default='apartment', max_length=16)),
                ('rooms', models.PositiveSmallIntegerField(default=1)),
                ('area', models.FloatField(help_text='Umumiy maydon, m²')),
                ('floor', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_floors', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('furnished', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_elevator', models.BooleanField(default=False)),
                ('has_ac', models.BooleanField(default=False)),
                ('has_internet', models.BooleanField(default=False)),
                ('family_ok', models.BooleanField(default=True)),
                ('students_ok', models.BooleanField(default=True)),
                ('min_rental_months', models.PositiveSmallIntegerField(default=1)),
                ('deposit', models.PositiveBigIntegerField(blank=True, help_text="Kafolat (so'm)", null=True)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('city', models.CharField(db_index=True, default='Toshkent', max_length=64)),
                ('district', models.CharField(db_index=True, max_length=64)),
                ('address_line', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_accuracy', models.CharField(choices=[('exact', 'Aniq manzil'), ('approximate', 'Taxminiy joylashuv')], default='exact', max_length=16)),
                ('amenities', models.ManyToManyField(blank=True, related_name='properties', to='listings.amenity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mulk',
                'verbose_name_plural': 'Mulklar',
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='prop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='listings.property'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('fake_listing', "Soxta e'lon"), ('not_available', 'Mavjud emas'), ('misleading_images', "Chalg'ituvchi rasmlar"), ('suspicious_price', 'Shubhali narx'), ('scam', 'Firibgarlik'), ('inappropriate', "Nojo'ya mazmun"), ('other', 'Boshqa')], max_length=24)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('in_review', "Ko'rib chiqilmoqda"), ('resolved', 'Hal qilingan'), ('dismissed', 'Rad etilgan')], db_index=True, default='new', max_length=12)),
                ('resolution_note', models.CharField(blank=True, max_length=500)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='chat.conversation')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='listings.listing')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shikoyat',
                'verbose_name_plural': 'Shikoyatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='listings.listing')),
            ],
            options={
                'verbose_name': "Saqlangan e'lon",
                'verbose_name_plural': "Saqlangan e'lonlar",
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'listing'), name='unique_favorite')],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'district'], name='listings_pr_city_a273fa_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type', 'rooms'], name='listings_pr_propert_408eb9_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', '-created_at'], name='listings_li_status_f5055b_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price'], name='listings_li_price_d6caaa_idx'),
        ),
    ]
