# Generated by Django 5.2.17 on 2026-08-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='phash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
