# Generated by Django 5.2.17 on 2026-08-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listingimage_phash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('draft', 'Qoralama'), ('pending_review', "Ko'rib chiqilmoqda"), ('ai_checking', 'AI tekshirilmoqda'), ('needs_review', "Qo'shimcha tekshiruv talab qilinadi"), ('approved', 'Tasdiqlangan'), ('published', "E'lon qilingan"), ('paused', "To'xtatilgan"), ('rejected', 'Rad etilgan'), ('expired', "Muddati o'tgan"), ('reserved', 'Band qilingan'), ('rented', 'Ijaraga berilgan'), ('deleted', "O'chirilgan")], db_index=True, default='draft', max_length=24),
        ),
    ]
