# Generated by Django 5.2.17 on 2026-08-18 12:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('listing_approved', "E'lon tasdiqlandi"), ('listing_rejected', "E'lon rad etildi"), ('listing_review', "E'lon tekshiruvda"), ('new_match', "Yangi mos e'lon"), ('price_changed', "Narx o'zgardi"), ('new_message', 'Yangi xabar'), ('report_update', 'Shikoyat holati'), ('verification_result', 'Tasdiqlash natijasi'), ('system', 'Tizim xabari')], max_length=24)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, max_length=1000)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx')],
            },
        ),
    ]
