# Generated by Django 5.2.17 on 2026-09-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('listing_approved', "E'lon tasdiqlandi"), ('listing_rejected', "E'lon rad etildi"), ('listing_review', "E'lon tekshiruvda"), ('new_match', "Yangi mos e'lon"), ('price_changed', "Narx o'zgardi"), ('new_message', 'Yangi xabar'), ('report_update', 'Shikoyat holati'), ('verification_result', 'Tasdiqlash natijasi'), ('admin_assignment', 'Admin tayinlangan'), ('reservation_request', "Band qilish so'rovi"), ('reservation_confirmed', 'Band qilish tasdiqlandi'), ('reservation_declined', 'Band qilish rad etildi'), ('reservation_superseded', 'Boshqa kishi band qildi'), ('system', 'Tizim xabari')], max_length=24),
        ),
    ]
