# Generated by Django 5.2.17 on 2026-08-18 12:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('passport', 'Pasport'), ('property_doc', 'Mulk hujjati'), ('ownership_cert', 'Egalik guvohnomasi'), ('utility_bill', "Kommunal to'lov kvitansiyasi"), ('other', 'Boshqa')], max_length=16)),
                ('file', models.FileField(upload_to='private/verification/')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('reviewing', "Ko'rib chiqilmoqda"), ('verified', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], db_index=True, default='pending', max_length=12)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('moderator_note', models.CharField(blank=True, max_length=500)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_documents', to='listings.listing')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tasdiqlash hujjati',
                'verbose_name_plural': 'Tasdiqlash hujjatlari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='verificatio_user_id_c3b376_idx')],
            },
        ),
    ]
