# Generated by Django 5.2.17 on 2026-08-18 12:22

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analyzer_type', models.CharField(choices=[('image', 'Rasm'), ('text', 'Matn'), ('price', 'Narx'), ('document', 'Hujjat')], max_length=16)),
                ('provider', models.CharField(help_text='gemini | mock | rules', max_length=32)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('score', models.FloatField(blank=True, null=True)),
                ('result', models.JSONField(default=dict)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('raw_response_reference', models.CharField(blank=True, help_text='Object key if raw data was persisted', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI tahlili',
                'verbose_name_plural': 'AI tahlillari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('level', models.CharField(choices=[('low', 'Past xavf'), ('medium', "O'rtacha xavf"), ('high', 'Yuqori xavf')], default='low', max_length=8)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('weights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Xavf bahosi',
                'verbose_name_plural': 'Xavf baholari',
                'ordering': ['-score'],
            },
        ),
    ]
