# Generated by Django 5.2.17 on 2026-08-18 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk', to='listings.listing'),
        ),
        migrations.AddIndex(
            model_name='aianalysis',
            index=models.Index(fields=['listing', 'analyzer_type'], name='ai_aianalys_listing_4f2e16_idx'),
        ),
        migrations.AddIndex(
            model_name='aianalysis',
            index=models.Index(fields=['provider', '-created_at'], name='ai_aianalys_provide_176917_idx'),
        ),
    ]
