# Generated by Django 5.2.17 on 2026-08-18 12:21

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.accounts.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqam +998XXXXXXXXX formatida bo'lishi kerak.", regex='^\\+998\\d{9}$')])),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True)),
                ('role', models.CharField(choices=[('tenant', 'Ijarachi'), ('owner', 'Uy egasi'), ('moderator', 'Moderator'), ('admin', 'Administrator')], default='tenant', max_length=16)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_profile_verified', models.BooleanField(default=False, help_text='Moderator tomonidan shaxs/mulk hujjatlari tekshirilgan.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('bio', models.TextField(blank=True, max_length=1000)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('city', models.CharField(blank=True, max_length=64)),
                ('trust_tier', models.CharField(choices=[('new_user', 'Yangi foydalanuvchi'), ('phone_verified', 'Telefon tasdiqlangan'), ('profile_verified', 'Profil tasdiqlangan'), ('trusted', 'Ishonchli foydalanuvchi'), ('business', 'Biznes')], default='new_user', max_length=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profillar',
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('phone', 'Telefon')], max_length=8)),
                ('purpose', models.CharField(choices=[('registration', "Ro'yxatdan o'tish"), ('password_reset', 'Parolni tiklash')], max_length=16)),
                ('code_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('verified', 'Tasdiqlangan'), ('expired', "Muddati o'tgan"), ('revoked', 'Bekor qilingan')], default='pending', max_length=8)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tasdiqlash',
                'verbose_name_plural': 'Tasdiqlashlar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'channel', 'purpose', 'status'], name='accounts_ve_user_id_166ee3_idx')],
            },
        ),
    ]
